### ISSUE TITLE
graceful-fs warnings will soon be errors

### ISSUE THREAD

**Issue by sam-github** [ForbesLindesay/thread-sleep#12]
This (somehow, its not in your dev deps, are you injecting it during travis builds?) depends on an old node-pre-gyp, which depends on an old tar, which depends on an old graceful-fs... which every time it installs warns:

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to fin
d it in the tree.
```

could you re-release with the latest node-pre-gyp, which doesn't have this problem?

**Comment by ForbesLindesay** [comment]
We no longer use node-pre-gyp as we have removed the native dependency.
