### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by ForbesLindesay** [ForbesLindesay/thread-sleep#2]
It works in Mac, but sadly doesn't yet seem to work in linux.  It would be great if someone could figure out how to get that fixed :)

**Comment by ForbesLindesay** [comment]
http://cylonjs.com/blog/2014/11/19/creating-multiplatform-precompiled-binaries-for-node-modules/ might be helpful.

**Comment by thlorenz** [comment]
You may need to supply the `--pthreads` flag on linux, like [I do here](https://github.com/thlorenz/learnuv/blob/master/learnuv.gyp#L7)

**Comment by ForbesLindesay** [comment]
Thanks.  I've added it for now.  Once I get it working I might try removing it again and see if it breaks.

**Comment by ForbesLindesay** [comment]
I had to force travis to update gcc on linux, but it now works everywhere apart from linux + clang.  I'm guessing it probably just needs an updated version of clang.  Does anyone know if people will need it working on clang or do most linux people use gcc?

**Comment by thlorenz** [comment]
I use clang on Linux although gcc is still more widely used.
Ideally it'd work in both cases ;)

**Comment by TimothyGu** [comment]
Any reason you used the C++ `std::this_thread::sleep_for(std::chrono::milliseconds())`?

[POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/functions/nanosleep.html):

> The _nanosleep()_ function shall cause the current thread to be suspended from execution until either the time interval specified by the rqtp argument has elapsed or a signal is delivered to the calling thread, and its action is to invoke a signal-catching function or to terminate the process.

It looks much more cross-platform. Haven't tried though.

**Comment by ForbesLindesay** [comment]
@TimothyGu that seems to work great on POSIX systems, but doesn't work on Windows.  Perhaps we could use different code for Windows vs. other platforms

**Comment by TimothyGu** [comment]
You can use a simple ifdef for Windows with the Sleep() function: http://msdn.microsoft.com/en-us/library/windows/desktop/ms686298%28v=vs.85%29.aspx

**Comment by TimothyGu** [comment]
This can probably be closed now as 51dc883 is committed.

**Comment by ForbesLindesay** [comment]
This does indeed seem to be working.  I've also got node-pre-gyp correctly publishing for linux.  Thanks @TimothyGu.  I definitely owe you one.

**Comment by TimothyGu** [comment]
Cool :)
