### ISSUE TITLE
iojs on windows

### ISSUE THREAD

**Issue by ForbesLindesay** [ForbesLindesay/thread-sleep#6]
I haven't come up with a good way to test iojs support on windows (or publish node-pre-gyp versions).  Ideally, nodist would support iojs and we could use that just like we use nvm for travis.

see https://github.com/marcelklehr/nodist/issues/72

**Comment by TimothyGu** [comment]
FWIW nodist is basically dead. We should take a look at alternatives like [nvm-windows](https://github.com/coreybutler/nvm-windows) (which is written in Go). There is also nvmw but it's written in Python and I don't want to add a new dependency.

**Comment by TimothyGu** [comment]
> There is also nvmw but it's written in Python and I don't want to add a new dependency.

Just kidding it only needs Python for node.js <0.8. Plus nvmw supports io.js but nvm-windows doesn't.

**Comment by TimothyGu** [comment]
See iojs/io.js@58a612ea9d. Seems like it just got a lot easier.

**Comment by TimothyGu** [comment]
Fixed in 893c1173a70aebda14f16789006710facc1a88c9.
