### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by ForbesLindesay** [ForbesLindesay/thread-sleep#9]
@TimothyGu It looks like there's been a lot of activity since the last release.  Do you feel like doing the honours?

**Comment by TimothyGu** [comment]
Yes I will once I fix Node.js 4.0.0 on AppVeyor.

**Comment by ForbesLindesay** [comment]
Awesome, Thanks!

**Comment by TimothyGu** [comment]
Finally, both Travis CI and AppVeyor are working now. 1.0.4 was released also.
